[package]
name = "sequencer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# reth-scroll
reth-scroll-primitives.workspace = true

# alloy
alloy-rpc-types-engine.workspace = true

# scroll-alloy
scroll-alloy-network.workspace = true
scroll-alloy-provider.workspace = true
scroll-alloy-rpc-types-engine.workspace = true

# rollup-node
scroll-engine.workspace = true
scroll-db.workspace = true
rollup-node-providers.workspace = true

# misc
futures.workspace = true
thiserror.workspace = true

[dev-dependencies]
reth-tracing = { git = "https://github.com/scroll-tech/reth.git" }
reth-e2e-test-utils.workspace = true
tokio.workspace = true

reth-scroll-node = { workspace = true, features = ["test-utils"] }
reth-db = { git = "https://github.com/scroll-tech/reth.git" }
reth-node-core = { git = "https://github.com/scroll-tech/reth.git" }
reth-node-builder = { git = "https://github.com/scroll-tech/reth.git", features = ["test-utils"] }
reth-provider = { workspace = true, features = ["test-utils"] }
reth-revm = { git = "https://github.com/scroll-tech/reth.git", features = ["test-utils"] }
reth-tasks.workspace = true

alloy-primitives.workspace = true
scroll-alloy-consensus.workspace = true
alloy-network.workspace = true
alloy-consensus.workspace = true
futures.workspace = true