[package]
name = "sequencer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
exclude.workspace = true

[dependencies]
# scroll-alloy
scroll-alloy-rpc-types-engine.workspace = true

# reth-scroll
reth-scroll-primitives.workspace = true

# rollup-node
scroll-primitives.workspace = true

# misc
futures.workspace = true
tokio.workspace = true

[lints]
workspace = true
