[package]
name = "rollup-node-sequencer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# reth-scroll
reth-scroll-primitives.workspace = true

# alloy
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-engine.workspace = true

# scroll-alloy
scroll-alloy-network.workspace = true
scroll-alloy-provider.workspace = true
scroll-alloy-rpc-types-engine.workspace = true

# rollup-node
scroll-engine.workspace = true
scroll-db = { workspace = true, features = ["test-utils"] }
rollup-node-providers.workspace = true

# misc
futures.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
jsonrpsee.workspace = true
rollup-node-sequencer.workspace = true
reth-tracing = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/sequencer-rn-integration" }
reth-e2e-test-utils.workspace = true
tokio.workspace = true

reth-scroll-node = { workspace = true, features = ["test-utils"] }
reth-db = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/sequencer-rn-integration" }
reth-node-core = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/sequencer-rn-integration" }
reth-node-builder = { git = "https://github.com/scroll-tech/reth.git", features = ["test-utils"], branch = "feat/sequencer-rn-integration" }
reth-provider = { workspace = true, features = ["test-utils"] }
reth-revm = { git = "https://github.com/scroll-tech/reth.git", features = ["test-utils"], branch = "feat/sequencer-rn-integration" }
reth-tasks.workspace = true
rollup-node-primitives.workspace = true

reth-rpc-api = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/sequencer-rn-integration" }
reth-rpc-layer = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/sequencer-rn-integration" }
scroll-engine = { workspace = true, features = ["test-utils"] }

alloy-primitives.workspace = true
scroll-alloy-consensus.workspace = true
alloy-network.workspace = true
alloy-consensus.workspace = true
futures.workspace = true
