version: '3'

services:
  rollup-node:
    image: scrolltech/rollup-node:v0.0.1-rc7
    platform: linux/amd64
    command: node --chain scroll-sepolia --datadir=/l2reth --metrics=0.0.0.0:6060 --disable-discovery --http --http.addr=0.0.0.0 --http.port=8545 --http.corsdomain '*'  --http.api admin,debug,eth,net,trace,txpool,web3,rpc,reth,ots,flashbots,miner,mev --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.api admin,debug,eth,net,trace,txpool,web3,rpc,reth,ots,flashbots,miner,mev --log.stdout.format log-fmt -vvv --l1.url http://l1geth-rpc.sepolia.scroll.tech:8545/l1 --l1.cups 10000 --eth-scroll-bridge.enabled --scroll-wire.enabled --optimistic-sync --builder.gaslimit 20000000 --trusted-peers enode://29cee709c400533ae038a875b9ca975c8abef9eade956dcf3585e940acd5c0ae916968f514bd37d1278775aad1b7db30f7032a70202a87fd7365bd8de3c9f5fc@44.242.39.33:30303
    ports:
      - "8545:8545"  # JSON-RPC
      - "8546:8546"  # WebSocket
      - "6060:6060"  # Metrics
    volumes:
      - ./l2reth:/l2reth