[package]
name = "rollup-node-providers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# alloy
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-engine.workspace = true
kona-providers-alloy = "0.2.0"

# scroll
scroll-alloy-consensus.workspace = true

# misc
async-trait.workspace = true

