[package]
name = "scroll-indexer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
exclude.workspace = true

[dependencies]
# rollup-node
scroll-l1.workspace = true
scroll-primitives.workspace = true

[lints]
workspace = true
