global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'rollup-node-metrics'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['rollup-node:6060']
        labels:
          client_name: "rollup-node"
          env: "mainnet"
          org: "scroll"
          service: 'rollup-node'
    fallback_scrape_protocol: "PrometheusText0.0.4"
