{
 "title": "Rollup node",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Indexer task handling duration",
   "type": "timeseries",
   "description": "The average duration of handling indexer tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(reth_indexer_task_duration_sum{item!=\"\"}[$__rate_interval]) / rate(reth_indexer_task_duration_count{item!=\"\"}[$__rate_interval])) by (item)",
     "legendFormat": "{{item}}"
    }
   ]
  },
  { "title": "Derivation pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Derived L2 payload attributes",
   "type": "timeseries",
   "description": "L2 attributes derived from the L1 by the derivation pipeline.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "attributes" } },
   "targets": [
    {
     "expr": "reth_derivation_pipeline_derived_blocks",
     "legendFormat": "attributes"
    },
    {
     "expr": "reth_derivation_pipeline_blocks_per_second",
     "legendFormat": "attributes/second"
    }
   ]
  },
  { "title": "L1 watcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Reorg depths",
   "type": "histogram",
   "description": "A histogram of the L1 reorg depths.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "reth_l1_watcher_reorg_depths", "legendFormat": "Reorg depth" }
   ]
  },
  {
   "title": "Sync status",
   "type": "timeseries",
   "description": "The current sync status of the L1 watcher.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "reth_l1_watcher_l1_messages", "legendFormat": "Indexed L1 messages" },
    { "expr": "reth_l1_watcher_batch_commits", "legendFormat": "Indexed batch commits" },
    {
     "expr": "reth_l1_watcher_batch_finalizations",
     "legendFormat": "Indexed batch finalizations"
    }
   ]
  },
  {
   "title": "Reorgs",
   "type": "timeseries",
   "description": "The L1 reorg count.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "reth_l1_watcher_reorgs", "legendFormat": "Reorgs" }
   ]
  }
 ]
}