{
 "title": "Reth - Transaction Pool",
 "description": "Metrics for transaction P2P gossip and the local view of mempool data",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "query_result(reth_info)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Build Timestamp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{build_timestamp}}"
    }
   ]
  },
  {
   "title": "Git SHA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{git_sha}}"
    }
   ]
  },
  {
   "title": "Build Profile",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{build_profile}}"
    }
   ]
  },
  {
   "title": "Target Triple",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{target_triple}}"
    }
   ]
  },
  {
   "title": "Cargo Features",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{cargo_features}}"
    }
   ]
  },
  { "title": "Transaction Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "instance" },
  {
   "title": "Blob store",
   "type": "timeseries",
   "description": "Tracks the entries, byte size, failed inserts and file deletes of the blob store",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "reth_transaction_pool_blobstore_entries{instance=~\"$instance\"}",
     "legendFormat": "Entries"
    },
    {
     "expr": "reth_transaction_pool_blobstore_byte_size{instance=~\"$instance\"}",
     "legendFormat": "Bytesize"
    },
    {
     "expr": "reth_transaction_pool_blobstore_failed_inserts{instance=~\"$instance\"}",
     "legendFormat": "Failed Inserts"
    },
    {
     "expr": "reth_transaction_pool_blobstore_failed_deletes{instance=~\"$instance\"}",
     "legendFormat": "Failed Deletes"
    }
   ]
  },
  {
   "title": "Subpool Sizes in Bytes",
   "type": "timeseries",
   "description": "Tracks a heuristic of the memory footprint of the various transaction pool sub-pools",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "reth_transaction_pool_basefee_pool_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Base Fee Pool Size"
    },
    {
     "expr": "reth_transaction_pool_pending_pool_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Pending Pool Size"
    },
    {
     "expr": "reth_transaction_pool_queued_pool_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Queued Pool Size"
    },
    {
     "expr": "reth_transaction_pool_blob_pool_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Blob Pool Size"
    }
   ]
  },
  {
   "title": "TxPool Maintenance",
   "type": "timeseries",
   "description": "Transaction pool maintenance metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "reth_transaction_pool_dirty_accounts{instance=~\"$instance\"}",
     "legendFormat": "Dirty Accounts"
    },
    {
     "expr": "reth_transaction_pool_drift_count{instance=~\"$instance\"}",
     "legendFormat": "Drift Count"
    },
    {
     "expr": "reth_transaction_pool_reinserted_transactions{instance=~\"$instance\"}",
     "legendFormat": "Reinserted Transactions"
    },
    {
     "expr": "reth_transaction_pool_deleted_tracked_finalized_blobs{instance=~\"$instance\"}",
     "legendFormat": "Deleted Tracked Finalized Blobs"
    }
   ]
  },
  {
   "title": "Subpool Transaction Count",
   "type": "timeseries",
   "description": "Tracks the number of transactions in the various transaction pool sub-pools",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "reth_transaction_pool_basefee_pool_transactions{instance=~\"$instance\"}",
     "legendFormat": "Base Fee Pool Transactions"
    },
    {
     "expr": "reth_transaction_pool_pending_pool_transactions{instance=~\"$instance\"}",
     "legendFormat": "Pending Pool Transactions"
    },
    {
     "expr": "reth_transaction_pool_queued_pool_transactions{instance=~\"$instance\"}",
     "legendFormat": "Queued Pool Transactions"
    },
    {
     "expr": "reth_transaction_pool_blob_pool_transactions{instance=~\"$instance\"}",
     "legendFormat": "Blob Pool Transactions"
    }
   ]
  },
  {
   "title": "Inserted Transactions",
   "type": "timeseries",
   "description": "Tracks the number of transactions per second that are inserted and removed from the transaction pool, as well as the number of invalid transactions per second.\n\nBad transactions are a subset of invalid transactions, these will never be successfully imported. The remaining invalid transactions have a chance of being imported, for example transactions with nonce gaps.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(reth_transaction_pool_inserted_transactions{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Inserted Transactions"
    },
    {
     "expr": "rate(reth_transaction_pool_removed_transactions{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Removed Transactions"
    },
    {
     "expr": "rate(reth_transaction_pool_invalid_transactions{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Invalid Transactions"
    },
    {
     "expr": "rate(reth_network_bad_imports{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Bad Transactions"
    }
   ]
  },
  {
   "title": "Pending Pool Imports",
   "type": "timeseries",
   "description": "Number of transactions about to be imported into the pool.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "reth_network_pending_pool_imports{instance=~\"$instance\"}",
     "legendFormat": "Transactions Pending Import"
    }
   ]
  },
  {
   "title": "Incoming Gossip and Requests",
   "type": "timeseries",
   "description": "Tracks the number of incoming transaction messages in the channel from the network to the transaction pool.\n\nMempool messages sent over this channel are `GetPooledTransactions` requests, `NewPooledTransactionHashes` announcements (gossip), and `Transactions` (gossip)\n\nTx - `NetworkManager`\n\\nRx - `TransactionsManager`",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(reth_network_pool_transactions_messages_sent_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Tx"
    },
    {
     "expr": "rate(reth_network_pool_transactions_messages_received_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Rx"
    },
    {
     "expr": "reth_network_pool_transactions_messages_sent_total{instance=~\"$instance\"} - reth_network_pool_transactions_messages_received_total{instance=~\"$instance\"}",
     "legendFormat": "Messages in Channel"
    }
   ]
  },
  {
   "title": "Queued Outgoing Messages",
   "type": "timeseries",
   "description": "Measures the message send rate (MPS) for queued outgoing messages. Outgoing messages are added to the queue before being sent to other peers, and this metric helps track the rate of message dispatch.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(reth_network_queued_outgoing_messages{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Queued Messages per Second"
    }
   ]
  },
  {
   "title": "All Transactions metrics",
   "type": "timeseries",
   "description": "All Transactions metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "reth_transaction_pool_all_transactions_by_hash{instance=~\"$instance\"}",
     "legendFormat": "All transactions by hash"
    },
    {
     "expr": "reth_transaction_pool_all_transactions_by_id{instance=~\"$instance\"}",
     "legendFormat": "All transactions by id"
    },
    {
     "expr": "reth_transaction_pool_all_transactions_by_all_senders{instance=~\"$instance\"}",
     "legendFormat": "All transactions by all senders"
    },
    {
     "expr": "reth_transaction_pool_blob_transactions_nonce_gaps{instance=~\"$instance\"}",
     "legendFormat": "Blob transactions nonce gaps"
    }
   ]
  },
  {
   "title": "Outgoing Capability Messages",
   "type": "timeseries",
   "description": "Egress RLPx capability traffic (default only `eth` capability)\n\nDropped - session channels are bounded, if there's no capacity, the message will be dropped.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(reth_network_total_outgoing_peer_messages_dropped{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Dropped"
    }
   ]
  },
  {
   "title": "Frequency of Transactions Already in Pool",
   "type": "timeseries",
   "description": "Total number of times a transaction is sent/announced that is already in the local pool.\n\nThis reflects the redundancy in the mempool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(reth_network_occurrences_hashes_already_in_pool{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Freq Announced Transactions Already in Pool"
    },
    {
     "expr": "rate(reth_network_occurrences_transactions_already_in_pool{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Freq Received Transactions Already in Pool "
    }
   ]
  },
  {
   "title": "Inflight Transaction Requests",
   "type": "timeseries",
   "description": "Currently active outgoing GetPooledTransactions requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "reth_network_inflight_transaction_requests{instance=~\"$instance\"}",
     "legendFormat": "Inflight Transaction Requests"
    }
   ]
  },
  {
   "title": "Transactions Manager Poll Duration",
   "type": "timeseries",
   "description": "Duration of one call to poll `TransactionsManager` future, and its nested function calls.\n\nNetwork Events - stream peer session updates from `NetworkManager`;\nTransaction Events - stream txns gossip from `NetworkManager`;\nPending Transactions - stream hashes of txns successfully inserted into pending set in `TransactionPool`;\nPending Pool Imports - flush txns to pool from `TransactionsManager`;\nFetch Events - stream fetch txn events (success case wraps a tx) from `TransactionFetcher`;\nFetch Pending Hashes - search for hashes announced by an idle peer in cache for hashes pending fetch;\n(Transactions Commands - stream commands from testnet to fetch/serve/propagate txns)\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_network_acc_duration_poll_network_events{instance=\"$instance\"}",
     "legendFormat": "Network Events"
    },
    {
     "expr": "reth_network_acc_duration_poll_transaction_events{instance=\"$instance\"}",
     "legendFormat": "Transaction Events"
    },
    {
     "expr": "reth_network_acc_duration_poll_imported_transactions{instance=\"$instance\"}",
     "legendFormat": "Pending Transactions"
    },
    {
     "expr": "reth_network_acc_duration_poll_pending_pool_imports{instance=\"$instance\"}",
     "legendFormat": "Pending Pool Imports"
    },
    {
     "expr": "reth_network_acc_duration_poll_fetch_events{instance=\"$instance\"}",
     "legendFormat": "Fetch Events"
    },
    {
     "expr": "reth_network_acc_duration_poll_commands{instance=\"$instance\"}",
     "legendFormat": "Commands"
    },
    {
     "expr": "reth_network_acc_duration_fetch_pending_hashes{instance=\"$instance\"}",
     "legendFormat": "Fetch Pending Hashes"
    },
    {
     "expr": "reth_network_duration_poll_tx_manager{instance=\"$instance\"}",
     "legendFormat": "Total Transactions Manager Future"
    }
   ]
  },
  {
   "title": "Transaction Fetcher Hashes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "reth_network_hashes_pending_fetch{instance=~\"$instance\"}",
     "legendFormat": "Hashes in Pending Fetch Cache"
    },
    {
     "expr": "reth_network_hashes_inflight_transaction_requests{instance=~\"$instance\"}",
     "legendFormat": "Hashes in Inflight Requests"
    },
    {
     "expr": "sum(reth_network_hashes_inflight_transaction_requests{instance=~\"$instance\"}) + sum(reth_network_hashes_pending_fetch{instance=~\"$instance\"})",
     "legendFormat": "Total Hashes in Transaction Fetcher"
    }
   ]
  },
  {
   "title": "Network Manager Poll Duration",
   "type": "timeseries",
   "description": "Durations of one call to poll `NetworkManager` future, and its nested function calls.\n\nNetwork Handle Message - stream network handle messages from `TransactionsManager`;\nSwarm Events - stream transaction gossip from `Swarm`",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_network_acc_duration_poll_network_handle{instance=\"$instance\"}",
     "legendFormat": "Network Handle Messages"
    },
    {
     "expr": "reth_network_acc_duration_poll_swarm{instance=\"$instance\"}",
     "legendFormat": "Swarm Events"
    },
    {
     "expr": "reth_network_duration_poll_network_manager{instance=\"$instance\"}",
     "legendFormat": "Total Network Manager Future"
    }
   ]
  },
  {
   "title": "Frequency of Transactions Already Marked as Seen by Peer",
   "type": "timeseries",
   "description": "Frequency of a peer sending a transaction that has already been marked as seen by that peer. This could for example be the case if a transaction is sent/announced to the peer at the same time that the peer sends/announces the same transaction to us.\n\nThis reflects the latency in the mempool.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(reth_network_occurrences_hash_already_seen_by_peer{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Freq Announced Transactions Already Seen by Peer"
    },
    {
     "expr": "rate(reth_network_occurrences_of_transaction_already_seen_by_peer{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Freq Received Transactions Already Seen by Peer"
    }
   ]
  },
  {
   "title": "Transactions by Type in Pool",
   "type": "timeseries",
   "description": "Number of all transactions of all sub-pools by type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "reth_transaction_pool_total_legacy_transactions{instance=\"$instance\"}",
     "legendFormat": "Legacy"
    },
    {
     "expr": "reth_transaction_pool_total_eip2930_transactions{instance=\"$instance\"}",
     "legendFormat": "EIP-2930"
    },
    {
     "expr": "reth_transaction_pool_total_eip1559_transactions{instance=\"$instance\"}",
     "legendFormat": "EIP-1559"
    },
    {
     "expr": "reth_transaction_pool_total_eip4844_transactions{instance=\"$instance\"}",
     "legendFormat": "EIP-4844"
    },
    {
     "expr": "reth_transaction_pool_total_eip7702_transactions{instance=\"$instance\"}",
     "legendFormat": "EIP-7702"
    }
   ]
  },
  {
   "title": "Fetch Hashes Pending Fetch Duration",
   "type": "timeseries",
   "description": "Duration of one call to `TransactionFetcher::on_fetch_pending_hashes`.\n\nFind Peer - find an idle fallback peer for a hash pending fetch.\n\nFill Request - fill `GetPooledTransactions` request, for the found peer, with more hashes from cache of hashes pending fetch. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_network_duration_find_idle_fallback_peer_for_any_pending_hash{instance=\"$instance\"}",
     "legendFormat": "Find Idle Peer"
    },
    {
     "expr": "reth_network_duration_fill_request_from_hashes_pending_fetch{instance=\"$instance\"}",
     "legendFormat": "Fill Request"
    }
   ]
  },
  {
   "title": "Announced Transactions by Type",
   "type": "timeseries",
   "description": "Frequency of transaction types seen in announcements",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(reth_network_transaction_fetcher_legacy_sum{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Legacy"
    },
    {
     "expr": "rate(reth_network_transaction_fetcher_eip2930_sum{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Eip2930"
    },
    {
     "expr": "rate(reth_network_transaction_fetcher_eip1559_sum{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Eip1559"
    },
    {
     "expr": "rate(reth_network_transaction_fetcher_eip4844_sum{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Eip4844"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 }, "repeat": "instance" },
  {
   "title": "Discovery: Tracked peers",
   "type": "timeseries",
   "description": "The number of tracked peers in the discovery modules (dnsdisc and discv4)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "reth_network_tracked_peers{instance=~\"$instance\"}",
     "legendFormat": "Tracked Peers"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "The number of incoming and outgoing connections, as well as the number of peers we are currently connected to. Outgoing and incoming connections also count peers we are trying to connect to.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 86 },
   "targets": [
    {
     "expr": "reth_network_pending_outgoing_connections{instance=~\"$instance\"}",
     "legendFormat": "Pending Outgoing Connections"
    },
    {
     "expr": "reth_network_outgoing_connections{instance=~\"$instance\"}",
     "legendFormat": "Outgoing Connections"
    },
    {
     "expr": "reth_network_total_pending_connections{instance=~\"$instance\"}",
     "legendFormat": "Total Pending Connections"
    },
    {
     "expr": "reth_network_incoming_connections{instance=~\"$instance\"}",
     "legendFormat": "Incoming Connections"
    },
    {
     "expr": "reth_network_connected_peers{instance=~\"$instance\"}",
     "legendFormat": "Connected Peers"
    }
   ]
  },
  {
   "title": "P2P Errors",
   "type": "timeseries",
   "description": "Internal errors in the P2P module. These are expected to happen from time to time. High error rates should not cause alarm if the node is peering otherwise.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(reth_p2pstream_disconnected_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "P2P Stream Disconnected"
    },
    {
     "expr": "rate(reth_network_pending_session_failures{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Failed Pending Sessions"
    },
    {
     "expr": "rate(reth_network_invalid_messages_received_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Invalid Messages"
    }
   ]
  },
  {
   "title": "Peer Disconnect Reasons",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 94 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_network_useless_peer{instance=~\"$instance\"}",
     "legendFormat": "UselessPeer"
    },
    {
     "expr": "reth_network_subprotocol_specific{instance=~\"$instance\"}",
     "legendFormat": "SubprotocolSpecific"
    },
    {
     "expr": "reth_network_already_connected{instance=~\"$instance\"}",
     "legendFormat": "AlreadyConnected"
    },
    {
     "expr": "reth_network_client_quitting{instance=~\"$instance\"}",
     "legendFormat": "ClientQuitting"
    },
    {
     "expr": "reth_network_unexpected_identity{instance=~\"$instance\"}",
     "legendFormat": "UnexpectedHandshakeIdentity"
    },
    {
     "expr": "reth_network_disconnect_requested{instance=~\"$instance\"}",
     "legendFormat": "DisconnectRequested"
    },
    {
     "expr": "reth_network_null_node_identity{instance=~\"$instance\"}",
     "legendFormat": "NullNodeIdentity"
    },
    {
     "expr": "reth_network_tcp_subsystem_error{instance=~\"$instance\"}",
     "legendFormat": "TCPSubsystemError"
    },
    {
     "expr": "reth_network_incompatible{instance=~\"$instance\"}",
     "legendFormat": "IncompatibleP2PVersion"
    },
    {
     "expr": "reth_network_protocol_breach{instance=~\"$instance\"}",
     "legendFormat": "ProtocolBreach"
    },
    {
     "expr": "reth_network_too_many_peers{instance=~\"$instance\"}",
     "legendFormat": "TooManyPeers"
    }
   ]
  },
  {
   "title": "Total Dial Success",
   "type": "timeseries",
   "description": "Number of successful outgoing dial attempts.",
   "gridPos": { "h": 8, "w": 14, "x": 8, "y": 94 },
   "targets": [
    {
     "expr": "reth_network_total_dial_successes{instance=~\"$instance\"}",
     "legendFormat": "Total Dial Successes"
    }
   ]
  }
 ]
}