[package]
name = "scroll-wire"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
reth-eth-wire = { git = "https://github.com/scroll-tech/reth.git" }
reth-primitives = { git = "https://github.com/scroll-tech/reth.git", default-features = false }
alloy-primitives = { version = "0.8.15", default-features = false, features = [
	"map-foldhash",
] }
alloy-rlp = { version = "0.3.10", default-features = false }
tokio = { version = "1.39", default-features = false, features = ["full"] }
tokio-stream = "0.1"
futures = "0.3"
reth-network = { git = "https://github.com/scroll-tech/reth.git" }
reth-network-api = { git = "https://github.com/scroll-tech/reth.git" }
reth-provider = { git = "https://github.com/scroll-tech/reth.git", features = ["test-utils"] }
reth-scroll-chainspec = { git = "https://github.com/scroll-tech/reth.git" }
eyre = "0.6"
