[package]
name = "gossip"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
exclude.workspace = true

[dependencies]
network.workspace = true
tokio = {version = "1.39", default-features = false, features = ["full"] }
scroll-wire.workspace = true
reth-network = { path = "../../../reth/crates/net/network" }
reth-network-peers = { path = "../../../reth/crates/net/peers" }
secp256k1 = { version = "0.29", default-features = false, features = [
    "global-context",
    "recovery",
] }
reth-node-core = { path = "../../../reth/crates/node/core" }
temp-dir = "0.1.14"
