version: '3'

services:
  l1-devnet:
    image: scrolltech/l1-devnet:v0.0.4
    container_name: l1-devnet
    entrypoint: ["bash", "/docker-compose/launch_l1.bash"]
    profiles:
      - shadow-fork
    env_file:
      - .env.shadow-fork
    environment:
      - ENV=${ENV}
      - FORK_BLOCK_NUMBER=${FORK_BLOCK_NUMBER}
    ports:
      - "8543:8545"  # JSON-RPC
      - "8544:8546"  # WebSocket
    volumes:
      - ./l1devnet:/l1devnet
    networks:
      - scroll-network

  rollup-node:
    image: scrolltech/rollup-node:v0.0.1-rc19
    container_name: rollup-node
    entrypoint: ["bash", "/docker-compose/launch_rollup_node.bash"]
    env_file:
      - .env.shadow-fork
    environment:
      - ENV=${ENV:-dev}
      - SHADOW_FORK=${SHADOW_FORK:-false}
      - RUST_LOG=sqlx=off,info
    ports:
      - "8545:8545"  # JSON-RPC
      - "8546:8546"  # WebSocket
      - "6060:6060"  # Metrics
    volumes:
      - ./l2reth:/l2reth
    networks:
      - scroll-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "19090:9090"  # Prometheus Web UI
    volumes:
      - ./resource/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1d'
      - '--storage.tsdb.retention.size=512MB'
      - '--storage.tsdb.wal-compression'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - scroll-network
    depends_on:
      - rollup-node

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "13000:3000"  # Grafana Web UI
    volumes:
      - ./resource/grafana-datasource.yml:/config/datasources/datasource.yml:ro
      - ./resource/grafana-dashboard-providers.yml:/config/dashboards/dashboard-providers.yml:ro
      - ./resource/dashboards:/dashboards:ro
      - ./grafana_data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/dashboards/overview.json
      - GF_PATHS_PROVISIONING=/config
    networks:
      - scroll-network
    depends_on:
      - prometheus

networks:
  scroll-network:
    driver: bridge
