[package]
name = "bridge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
exclude.workspace = true

[dependencies]
# reth
reth-cli-util = { git = "https://github.com/scroll-tech/reth.git" }
reth-network.workspace = true
reth-network-peers.workspace = true
reth-node-api = { git = "https://github.com/scroll-tech/reth.git" }
reth-node-builder = { git = "https://github.com/scroll-tech/reth.git" }
reth-node-types = { git = "https://github.com/scroll-tech/reth.git" }
reth-primitives.workspace = true
reth-provider.workspace = true
reth-tracing = { git = "https://github.com/scroll-tech/reth.git" }
reth-transaction-pool = { git = "https://github.com/scroll-tech/reth.git" }

# scroll
reth-scroll-chainspec.workspace = true
reth-scroll-cli = { git = "https://github.com/scroll-tech/reth.git" }
reth-scroll-node = { git = "https://github.com/scroll-tech/reth.git" }
scroll-wire.workspace = true
network.workspace = true

# misc
clap = { version = "4", features = ["derive", "env"] }
eyre = "0.6"
secp256k1 = { version = "0.29", default-features = false, features = [
    "global-context",
    "recovery",
] }
tokio = {version = "1.39", default-features = false, features = ["full"] }
tracing = "0.1.0"


[features]
scroll = [
	"reth-provider/scroll",
	"reth-scroll-cli/scroll",
]
skip-state-root-validation = [
	"reth-node-builder/skip-state-root-validation",
	"reth-scroll-node/skip-state-root-validation",
	"reth-provider/skip-state-root-validation"
]
optimism = [
	"reth-provider/optimism",
	"reth-scroll-cli/optimism",
	"reth-scroll-node/optimism"
]

[[bin]]
name = "bridge"
path = "src/main.rs"
required-features = ["skip-state-root-validation", "scroll"]
