[package]
name = "scroll-bridge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
exclude.workspace = true

[dependencies]
# alloy
alloy-consensus = { version = "0.9.2", default-features = false }

# reth
reth-cli-util = { git = "https://github.com/scroll-tech/reth.git" }
reth-eth-wire-types.workspace = true
reth-network.workspace = true
reth-network-peers.workspace = true
reth-node-api = { git = "https://github.com/scroll-tech/reth.git" }
reth-node-builder = { git = "https://github.com/scroll-tech/reth.git" }
reth-node-core = { git = "https://github.com/scroll-tech/reth.git" }
reth-node-types = { git = "https://github.com/scroll-tech/reth.git" }
reth-primitives.workspace = true
reth-provider.workspace = true
reth-transaction-pool = { git = "https://github.com/scroll-tech/reth.git" }

# scroll
reth-scroll-chainspec.workspace = true
reth-scroll-cli = { git = "https://github.com/scroll-tech/reth.git" }
reth-scroll-node = { git = "https://github.com/scroll-tech/reth.git" }
scroll-wire.workspace = true
scroll-network.workspace = true

# misc
clap = { version = "4", features = ["derive", "env"] }
eyre.workspace = true
secp256k1 = { workspace = true, features = [
    "global-context",
    "recovery",
] }
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true

[dev-dependencies]
# alloy
alloy-primitives = { workspace = true, default-features = false, features = [
    "map-foldhash",
] }
alloy-genesis = { version = "0.9.2", default-features = false }
alloy-rpc-types-engine.workspace = true

# reth
reth-e2e-test-utils = { git = "https://github.com/scroll-tech/reth.git" }
reth-payload-builder = { git = "https://github.com/scroll-tech/reth.git" }
reth-rpc-server-types = { git = "https://github.com/scroll-tech/reth.git" }
reth-tasks.workspace = true
reth-tracing = { git = "https://github.com/scroll-tech/reth.git" }

# misc
serde_json = { version = "1.0.94", default-features = false, features = ["alloc"] }


[features]
scroll = [
	"reth-provider/scroll",
	"reth-scroll-cli/scroll",
]
skip-state-root-validation = [
	"reth-node-builder/skip-state-root-validation",
	"reth-scroll-node/skip-state-root-validation",
	"reth-provider/skip-state-root-validation"
]
optimism = [
	"reth-provider/optimism",
	"reth-scroll-cli/optimism",
	"reth-scroll-node/optimism",
	"reth-node-core/optimism",
	"reth-primitives/optimism"
]

[[bin]]
name = "bridge"
path = "src/main.rs"
required-features = ["skip-state-root-validation", "scroll"]
