[package]
name = "scroll-bridge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
exclude.workspace = true

[dependencies]
# alloy
alloy-rpc-types-engine.workspace = true

# scroll-alloy
scroll-alloy-consensus = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/add-deref-blanket-engine-api" }
scroll-alloy-network = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/add-deref-blanket-engine-api" }
scroll-alloy-rpc-types-engine= { git = "https://github.com/scroll-tech/reth.git", branch = "feat/add-deref-blanket-engine-api" }
scroll-alloy-provider.workspace = true

# reth
reth-cli-util = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/add-deref-blanket-engine-api" }
reth-eth-wire-types.workspace = true
reth-network.workspace = true
reth-network-peers.workspace = true
reth-node-api = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/add-deref-blanket-engine-api", features = ["scroll"] }
reth-node-builder = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/add-deref-blanket-engine-api", features = ["skip-state-root-validation"] }
reth-node-core = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/add-deref-blanket-engine-api" }
reth-node-types = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/add-deref-blanket-engine-api" }
reth-primitives.workspace = true
reth-provider = { workspace = true, features = ["scroll", "skip-state-root-validation"]}
reth-rpc-api = { workspace = true, features = ["client"] }
reth-transaction-pool = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/add-deref-blanket-engine-api" }

# scroll
reth-scroll-chainspec.workspace = true
reth-scroll-cli = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/add-deref-blanket-engine-api", features = ["scroll"] }
reth-scroll-engine-primitives = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/add-deref-blanket-engine-api" }
reth-scroll-node = { workspace = true, features = ["skip-state-root-validation"] }
reth-scroll-primitives = { workspace = true, features = ["serde"] }
scroll-wire.workspace = true
scroll-network.workspace = true
scroll-engine = { workspace = true, features = ["test-utils"] }

# rollup-node
rollup-node-manager.workspace = true

# misc
clap = { version = "4", features = ["derive", "env"] }
eyre.workspace = true
futures.workspace = true
secp256k1 = { workspace = true, features = [
    "global-context",
    "recovery",
] }
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true

[dev-dependencies]
# alloy
alloy-primitives = { workspace = true, default-features = false, features = [
    "map-foldhash",
] }
alloy-rpc-types-engine.workspace = true

# reth
reth-e2e-test-utils = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/add-deref-blanket-engine-api" }
reth-payload-builder = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/add-deref-blanket-engine-api" }
reth-rpc-server-types = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/add-deref-blanket-engine-api" }
reth-tasks.workspace = true
reth-tracing = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/add-deref-blanket-engine-api" }

# misc
serde_json = { version = "1.0.94", default-features = false, features = ["alloc"] }
tokio = { workspace = true, features = ["full"] }

[features]
test-utils = [
	"reth-network/test-utils",
	"reth-node-builder/test-utils",
	"reth-primitives/test-utils",
	"reth-provider/test-utils",
	"reth-transaction-pool/test-utils",
	"scroll-engine/test-utils",
]

[[bin]]
name = "bridge"
path = "src/main.rs"
