[package]
name = "scroll-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# alloy
alloy-eips = { version = "0.9.2", default-features = false }
alloy-primitives.workspace = true
alloy-rpc-types-engine.workspace = true

# scroll-alloy
scroll-alloy-network.workspace = true
scroll-alloy-provider.workspace = true
scroll-alloy-rpc-types-engine = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/add-deref-blanket-engine-api" }

# reth
reth-engine-primitives = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/add-deref-blanket-engine-api", default-features = false, features = ["scroll"] }
reth-network-peers.workspace = true
reth-payload-primitives = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/add-deref-blanket-engine-api" }
reth-primitives = { workspace = true }

# reth-scroll
reth-scroll-primitives = { workspace = true, features = ["scroll"] }
reth-scroll-engine-primitives = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/add-deref-blanket-engine-api", default-features = false, features = ["scroll"] }

# misc
async-trait = "0.1.68"
eyre.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio.workspace = true
tracing.workspace = true

# test-utils
arbitrary = { version = "1.3", optional = true }

[dev-dependencies]
arbitrary = "1.3"
reth-testing-utils = { git = "https://github.com/scroll-tech/reth.git", branch = "feat/add-deref-blanket-engine-api" }

[features]
arbitrary = [
	"alloy-primitives/arbitrary",
	"reth-primitives/arbitrary",
	"alloy-eips/arbitrary",
	"reth-scroll-primitives/arbitrary",
	"scroll-alloy-rpc-types-engine/arbitrary"
]
test-utils = [
	"arbitrary",
	"dep:arbitrary",
	"reth-primitives/test-utils"
]
serde = [
	"alloy-eips/serde",
	"alloy-primitives/serde",
	"alloy-rpc-types-engine/serde",
	"reth-scroll-primitives/serde",
	"scroll-alloy-rpc-types-engine/serde"
]
