[package]
name = "engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# alloy
alloy-eips = { version = "0.9.2", default-features = false }
alloy-primitives.workspace = true
alloy-rpc-types-engine.workspace = true

# reth
reth-engine-primitives = { git = "https://github.com/scroll-tech/reth.git", default-features = false, features = ["scroll"] }
reth-primitives.workspace = true
reth-rpc-api = { git = "https://github.com/scroll-tech/reth.git", default-features = false, features = ["client"] }

# reth-scroll
reth-scroll-primitives = { workspace = true, features = ["serde", "scroll", "reth-codec"] }

# misc
eyre.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio.workspace = true
tracing.workspace = true

# test-utils
arbitrary = { version = "1.3", optional = true }

[dev-dependencies]
arbitrary = "1.3"
reth-testing-utils = { git = "https://github.com/scroll-tech/reth.git" }

[features]
arbitrary = [
    "alloy-primitives/arbitrary",
    "reth-primitives/arbitrary",
    "alloy-eips/arbitrary",
    "reth-scroll-primitives/arbitrary"
]
test_utils = [
    "arbitrary",
    "dep:arbitrary"
]
