use reth_scroll_primitives::ScrollBlock;
use rollup_node_primitives::{BatchInfo, L2BlockInfoWithL1Messages};
use scroll_network::BlockImportOutcome;

/// An enum representing the events that can be emitted by the engine driver.
#[derive(Debug)]
pub enum EngineDriverEvent {
    /// A new block has been generated by the engine driver.
    NewPayload(ScrollBlock),
    /// The result of attempting a block import.
    BlockImportOutcome(BlockImportOutcome),
    /// A block derived from L1 has been consolidated.
    L1BlockConsolidated((L2BlockInfoWithL1Messages, BatchInfo)),
}
