[package]
name = "network"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
exclude.workspace = true

[dependencies]
# alloy
alloy-primitives = { workspace = true, features = [
    "map-foldhash",
] }

# reth
reth-discv5 = { git = "https://github.com/scroll-tech/reth.git" }
reth-eth-wire-types = { git = "https://github.com/scroll-tech/reth.git" }
reth-network.workspace = true
reth-network-api.workspace = true
reth-network-types = { git = "https://github.com/scroll-tech/reth.git" }
reth-network-peers.workspace = true
reth-primitives.workspace = true
reth-storage-api = { git = "https://github.com/scroll-tech/reth.git" }
reth-tasks = { git = "https://github.com/scroll-tech/reth.git" }

# scroll
reth-scroll-chainspec.workspace = true
scroll-wire.workspace = true

# misc
futures = "0.3"
parking_lot = "0.12"
secp256k1 = { version = "0.29", default-features = false, features = ["global-context", "rand-std", "recovery"] }
tokio = {version = "1.39", default-features = false, features = ["full"] }
tokio-stream = "0.1"
tracing = "0.1.0"
