[package]
name = "network"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
exclude.workspace = true

[dependencies]
reth-eth-wire-types = { path = "../../../reth/crates/net/eth-wire-types" }
reth-network = { path = "../../../reth/crates/net/network" }
reth-network-api = { path = "../../../reth/crates/net/network-api" }
reth-network-types = { path = "../../../reth/crates/net/network-types" }
reth-network-peers = { path = "../../../reth/crates/net/peers" }
reth-primitives = { path = "../../../reth/crates/primitives" }
reth-discv5 = { path = "../../../reth/crates/net/discv5" }
reth-tasks = { path = "../../../reth/crates/tasks" }
reth-storage-api = { path = "../../../reth/crates/storage/storage-api" }
tokio = {version = "1.39", default-features = false, features = ["full"] }
tokio-stream = "0.1"
scroll-wire = { path = "../scroll-wire" }
alloy-primitives = { version = "0.8.15", default-features = false, features = [
    "map-foldhash",
] }
secp256k1 = { version = "0.29", default-features = false, features = ["global-context", "rand-std", "recovery"] }
parking_lot = "0.12"
futures = "0.3"
reth-scroll-chainspec = { path = "../../../reth/crates/scroll/chainspec" }
tracing = "0.1.0"
