[package]
name = "network"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
exclude.workspace = true

[dependencies]
reth-eth-wire-types = { git = "https://github.com/scroll-tech/reth.git" }
reth-network = { git = "https://github.com/scroll-tech/reth.git" }
reth-network-api = { git = "https://github.com/scroll-tech/reth.git" }
reth-network-types = { git = "https://github.com/scroll-tech/reth.git" }
reth-network-peers = { git = "https://github.com/scroll-tech/reth.git" }
reth-primitives = { git = "https://github.com/scroll-tech/reth.git" }
reth-discv5 = { git = "https://github.com/scroll-tech/reth.git" }
reth-tasks = { git = "https://github.com/scroll-tech/reth.git" }
reth-storage-api = { git = "https://github.com/scroll-tech/reth.git" }
tokio = {version = "1.39", default-features = false, features = ["full"] }
tokio-stream = "0.1"
scroll-wire.workspace = true
alloy-primitives = { version = "0.8.15", default-features = false, features = [
    "map-foldhash",
] }
secp256k1 = { version = "0.29", default-features = false, features = ["global-context", "rand-std", "recovery"] }
parking_lot = "0.12"
futures = "0.3"
reth-scroll-chainspec = { git = "https://github.com/scroll-tech/reth.git" }
tracing = "0.1.0"
