[package]
name = "scroll-network"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
exclude.workspace = true

[dependencies]
# alloy
alloy-primitives = { workspace = true, features = [
    "map-foldhash",
] }

# reth
reth-network.workspace = true
reth-network-api.workspace = true
reth-network-peers.workspace = true
reth-primitives.workspace = true
reth-storage-api = { git = "https://github.com/scroll-tech/reth.git" }

# scroll
reth-scroll-chainspec.workspace = true
reth-scroll-node = { workspace = true, features = ["skip-state-root-validation", "scroll"] }
reth-scroll-primitives.workspace = true
scroll-wire.workspace = true

# misc
futures.workspace = true
secp256k1 = { workspace = true, features = ["global-context", "rand-std", "recovery"] }
tokio = { workspace = true, features = ["full"] }
tokio-stream.workspace = true
tracing.workspace = true
