name: test

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  unit:
    runs-on:
      group: scroll-reth-runner-group
    timeout-minutes: 60
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v5
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: 'nightly'
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest@0.9.98
      - name: Run unit tests
        run: cargo nextest run --all-features --workspace --locked -E '!kind(test)'

  integration:
    runs-on:
      group: scroll-reth-runner-group
    timeout-minutes: 60
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v5
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: 'nightly'
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest@0.9.98
      - name: Run integration tests
        run: |
          cargo nextest run --all-features --workspace --locked \
            --no-tests=pass -E 'kind(test) and not test(docker)' \
            -- --skip test_should_consolidate_to_block_15k

  integration-docker-compose:
    runs-on:
      group: scroll-reth-runner-group
    timeout-minutes: 90
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v5
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest@0.9.98
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Free up disk space
        run: |
          echo "Initial disk usage:"
          df -h
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /usr/local/share/boost || true
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /usr/local/share/powershell || true
          sudo rm -rf /usr/share/swift || true
          sudo rm -rf /opt/hostedtoolcache || true
          echo "Disk usage after cleanup:"
          df -h
      - name: Run Docker Compose integration tests
        run: |
          cargo nextest run --all-features --workspace --locked \
            --no-tests=pass -E 'test(docker)' --test-threads=1 \
            --failure-output immediate \
            --success-output never \
            --verbose
        env:
          RUST_LOG: debug
          RUST_BACKTRACE: full
