name: test

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: 'nightly'
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          shared-key: "unit-tests"
          cache-targets: "false"
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest@0.9.98
      - name: Run unit tests
        run: cargo nextest run --all-features --workspace --locked -E '!kind(test)'

  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: 'nightly'
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          shared-key: "integration-tests"
          cache-targets: "false"
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest@0.9.98
      - name: Run integration tests
        run: |
          cargo nextest run --all-features --workspace --locked \
            --no-tests=pass -E 'kind(test)' \
            -- --skip test_should_consolidate_to_block_15k

  integration-docker-compose:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v4
      - name: Free disk space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          sudo apt-get clean
          docker system prune -af
          df -h
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          shared-key: "docker-compose-tests"
          cache-targets: "false"
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest@0.9.98
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:v0.12.0
      - name: Run Docker Compose integration tests
        run: cargo nextest run --all-features --workspace --locked --no-tests=pass -E 'test(docker)' --test-threads=1
      - name: Clean up Docker
        if: always()
        run: |
          docker system prune -af
          docker volume prune -f
