name: test

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: 'nightly'
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest@0.9.98
      - name: Run unit tests
        run: cargo nextest run --all-features --workspace --locked -E '!kind(test)'

  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: 'nightly'
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest@0.9.98
      - name: Run integration tests
        run: |
          cargo nextest run --all-features --workspace --locked \
            --no-tests=pass -E 'kind(test)' \
            -- --skip test_should_consolidate_to_block_15k

  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Run consolidation test
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
          RUST_LOG: "sqlx=off,info,scroll::engine=debug"
        run: |
          cargo test --release -p rollup-node test_should_consolidate_to_block_15k
